name: Mirrors

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  main:
    if: github.repository == 'sylirre/vmConsole'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to GitLab
        env:
          SSH_KEY: ${{ secrets.GITLAB_PUSH_MIRRORING_SSH_KEY }}
        run: |
          mkdir -p "$HOME"/.ssh
          echo "$SSH_KEY" > "$HOME"/.ssh/id_rsa
          chmod 600 "$HOME"/.ssh/id_rsa

          cat > "$HOME"/.ssh/known_hosts <<- EOF
          gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
          gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
          gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
          EOF

          git remote add gitlab git@gitlab.com:sylirre/vmconsole.git
          git push gitlab main
          git push --tags gitlab main
